 CREATE TABLE cliente (
          id integer GENERATED BY DEFAULT AS IDENTITY,
          limite int NOT NULL,
          saldo int NOT NULL,
          CONSTRAINT "PK_cliente" PRIMARY KEY (id)
      );


 CREATE TABLE transacao (
          id integer GENERATED BY DEFAULT AS IDENTITY,
          id_cliente integer NOT NULL,
          valor int NOT NULL,
          tipo varchar(1) NOT NULL,
          descricao varchar(10) NOT NULL,
          realizado_em timestamp with time zone NOT NULL,
          CONSTRAINT "PK_transacao" PRIMARY KEY (id),
          CONSTRAINT "FK_transacao_cliente_id_cliente" FOREIGN KEY (id_cliente) REFERENCES cliente (id)
      );
	  
	      CREATE INDEX "IX_transacao_id_cliente" ON transacao (id_cliente);


      INSERT INTO cliente (id, limite, saldo)
      VALUES (1, 100000, 0);
      INSERT INTO cliente (id, limite, saldo)
      VALUES (2, 80000, 0);
      INSERT INTO cliente (id, limite, saldo)
      VALUES (3, 1000000, 0);
      INSERT INTO cliente (id, limite, saldo)
      VALUES (4, 10000000, 0);
      INSERT INTO cliente (id, limite, saldo)
      VALUES (5, 500000, 0);
